- name: Install PHP with popular extensions
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - php5
    - php5-common
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-mcrypt
    - php5-intl
    - php5-json

- name: Copy PHP settings files
  template:
    src=php.ini.j2
    dest={{ php.settings_pathes[item.key] }}
  sudo: yes
  with_dict: php.settings
  notify: apache-restart
