- name: Install git
  apt: pkg=git
  sudo: yes

- name: Push global config file
  template:
    src=gitconfig.j2
    dest=/etc/gitconfig
    mode=0644
  sudo: yes

- name: Clone all repositories to local cache and checkout them to the HEAD
  local_action:
    git
      repo={{ item.value }}
      dest={{ git.local_cache_path }}/{{ item.key }}
      accept_hostkey=yes
      update=yes
      version=HEAD
      force=yes
  with_dict: git.repositories

- name: Sync git local cache with git remote cache
  synchronize:
    src={{ git.local_cache_path }}/
    dest={{ git.remote_cache_path }}/
    delete=yes
