- name: Install git
  apt: pkg=git
  sudo: yes

- name: Push global config file
  template:
    src=gitconfig.j2
    dest=/etc/gitconfig
    mode=0644
  sudo: yes

- name: Clone all repositories to local cache and checkout them to the HEAD
  local_action:
    git
      repo={{ item.value }}
      dest={{ git.local_cache_path }}/git/{{ item.key }}
      accept_hostkey=yes
  with_dict: git.repositories

- name: Archive local cache
  local_action:
    command
      tar czf {{ git.local_cache_path }}/git-cache.tar.gz git
      chdir={{ git.local_cache_path }}
      creates={{ git.local_cache_path }}/git-cache.tar.gz

- name: Unarchive local cache to the remote cache
  unarchive:
    src={{ git.local_cache_path }}/git-cache.tar.gz
    dest={{ git.remote_cache_path }}/
