- name: Install git
  apt: pkg=git
  sudo: yes

- name: Push global config file
  template:
    src=gitconfig.j2
    dest=/etc/gitconfig
    mode=0644
  sudo: yes

# TODO: remove after dropping support for ansible versions before 1.5
- name: Checkout all repositories to local cache (Ubuntu behind 14.04)
  local_action:
    git
      repo={{ item.url }}
      dest={{ git.local_cache_path }}/git/{{ item.directory }}
      version={{ item.version | default('HEAD') }}
  with_items: git.repositories
  when: ansible_distribution_version < '14.04'

- name: Checkout all repositories to local cache (Ubuntu 14.04 and above)
  local_action:
    git
      repo={{ item.url }}
      dest={{ git.local_cache_path }}/git/{{ item.directory }}
      version={{ item.version | default('HEAD') }}
      accept_hostkey=yes
  with_items: git.repositories
  when: ansible_distribution_version >= '14.04'

- name: Archive local cache
  local_action:
    command
      tar czf {{ git.local_cache_path }}/git-cache.tar.gz git
      chdir={{ git.local_cache_path }}
      creates={{ git.local_cache_path }}/git-cache.tar.gz

- name: Unarchive local cache to the remote cache
  unarchive:
    src={{ git.local_cache_path }}/git-cache.tar.gz
    dest={{ git.remote_cache_path }}/
