- name: Update and then safe upgrade installed packages
  apt:
    update_cache=yes
    upgrade=yes
  sudo: yes

# Next is Dropbox and PhpStorm issue:
#
# Dropbox:
# echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p
#
# PhpStorm:
# http://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
# 1. In file "/etc/sysctl.conf" change/add row: "fs.inotify.max_user_watches = 524288"
# 2. Then "sudo sysctl -p" to apply changes immediately

- name: Modify fs.inotify.max_user_watches in sysctl.conf
  lineinfile:
    dest=/etc/sysctl.conf
    regexp='^fs\.inotify\.max_user_watches'
    line="fs.inotify.max_user_watches = {{ preconf.sysctl.fs.inotify.max_user_watches }}"
  sudo: yes
  notify: sysctl-apply
